// types.ts
// Defines the TypeScript types used across the dashboard application.

/**
 * Type definition for a Product.
 * @property {string} id - Unique identifier for the product.
 * @property {string} name - Name of the product.
 * @property {string} description - Description of the product.
 * @property {number} price - Price of the product.
 * @property {number} stock - Current stock quantity of the product.
 * @property {number} ordersReceived - Number of orders received for this product.
 * @property {string} imageUrl - URL for the product image.
 */
export type Product = {
  id: string;
  name: string;
  description: string;
  price: number;
  stock: number;
  ordersReceived: number;
  imageUrl: string;
};

/**
 * Type definition for a single sales data point.
 * @property {string} name - Month name (e.g., 'Jan').
 * @property {number} sales - Sales figure for the month.
 */
type SalesDataPoint = {
  name: string;
  sales: number;
};

/**
 * Type definition for a top product entry.
 * @property {number} id - Unique identifier for the top product.
 * @property {string} name - Name of the top product.
 * @property {number} sales - Sales quantity of the top product.
 * @property {number} revenue - Revenue generated by the top product.
 */
type TopProduct = {
  id: number;
  name: string;
  sales: number;
  revenue: number;
};

/**
 * Type definition for a recent order entry.
 * @property {string} id - Order ID.
 * @property {string} customer - Customer name.
 * @property {number} total - Total amount of the order.
 * @property {string} status - Status of the order (e.g., 'Completed', 'Processing').
 * @property {string} date - Date of the order.
 */
type RecentOrder = {
  id: string;
  customer: string;
  total: number;
  status: string;
  date: string;
};

/**
 * Type definition for a customer segment entry.
 * @property {string} name - Name of the customer segment.
 * @property {number} value - Number of customers in the segment.
 */
type CustomerSegment = {
  name: string;
  value: number;
};

/**
 * Type definition for the main dashboard overview data.
 * @property {number} totalRevenue - Total revenue generated.
 * @property {number} totalOrders - Total number of orders.
 * @property {number} averageOrderValue - Average value per order.
 * @property {number} newCustomers - Number of new customers.
 * @property {number} activeStores - Number of active stores.
 * @property {number} gmvProcessed - Gross Merchandise Volume processed.
 * @property {string} uptime - System uptime percentage.
 * @property {string} globalReach - Global reach description.
 * @property {SalesDataPoint[]} salesData - Array of sales data points.
 * @property {TopProduct[]} topProducts - Array of top products.
 * @property {RecentOrder[]} recentOrders - Array of recent orders.
 * @property {CustomerSegment[]} customerSegments - Array of customer segments.
 */
export type DashboardData = {
  totalRevenue: number;
  totalOrders: number;
  averageOrderValue: number;
  newCustomers: number;
  activeStores: number;
  gmvProcessed: number;
  uptime: string;
  globalReach: string;
  salesData: SalesDataPoint[];
  topProducts: TopProduct[];
  recentOrders: RecentOrder[];
  customerSegments: CustomerSegment[];
};
